#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:nil author:t
#+OPTIONS: c:nil creator:comment d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: Org-citeproc TODO list
#+AUTHOR: Richard Lawrence
#+EMAIL: richard.lawrence@berkeley.edu
#+DESCRIPTION:
#+LANGUAGE: en
#+CREATOR: Emacs 23.4.1 (Org mode 8.3beta)
#+TAGS: bug(b) newfeature(f) refactor(r) maybe(m)
#+SEQ_TODO: TODO INPROGRESS WAITING UPSTREAM | DONE WONTFIX

* DONE Warning-free compilation					   :refactor:
  - [X] remaining warning: Cite's JSON instance is an `orphan'
    instance, because neither Cite nor JSON is defined in
    org-citeproc.hs
* INPROGRESS Correct cabal packaging				   :refactor:
  - [X] rename everything to `org-citeproc'
  - [ ] separate code into modules?
* INPROGRESS Add support for multi-cite citations		 :newfeature:
  - [X] handle common prefix and suffix
  - [X] support LaTeX-like behavior, where citation command
    distributes over each reference
    (e.g.  [cite: pre1 @Doe1999 post1; pre2 @Doe2000 post2] should
    render like: Doe (pre1 1999, post1), and Doe (pre2 2000, post2)
    rather than: Doe (pre1 1999, post1; pre2 Doe 2000 post2)
  - [X] add spaces after common-prefix and before common-suffix.  Org
    parser seems to delete these even if they appear in the source,
    but I can't see how they would be useful unless spaces are added.
    BibLateX inserts space after common prefix, comma and space
    before common suffix, in both \parencites and \textcites.
  - [ ] Internationalization or style-specific separators needed?
* TODO Add support for linking citations to bib entries		 :newfeature:
Cf. http://article.gmane.org/gmane.emacs.orgmode/96141

Looks like Pandoc might already be able to support this if we use
Text.Pandoc.Definition.Citation rather than Text.CSL.Style.Cite?  See
processCites in Text.CSL.Pandoc

** TODO Add unique IDs to bibliography entries
** TODO Optionally wrap citations in links to corresponding entries

* TODO Add support for Zotero-style metadata		   :newfeature:maybe:
Cf. http://article.gmane.org/gmane.emacs.orgmode/96154

* DONE Fix ODT writer							:bug:
As things are currently designed, the ODT writer does not place tags
in the right places.  It:
  - includes the citation ending marker inside a <text:p>; it should
    go outside
  - wraps the separator between citations and bibliography in a
    <text:p>
Curiously, the HTML writer does work, so I'm wondering if this is a
bug on the Pandoc side.  There are two ODT writers in Pandoc; possibly
the writer I'm using is not up to date.

* TODO Elisp writer?					   :newfeature:maybe:
This would be one way of making it easy for users to post-process
citations (e.g. via a filter) on the Org side.  If we can generate
Elisp that will be read as Org elements/objects, filters can
manipulate those objects, rather than worrying about parsing text in
the target format.
